# Generated by Django 3.1.2 on 2020-11-29 21:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('course_reference_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('subject_id', models.CharField(max_length=3)),
                ('number_id', models.CharField(max_length=4)),
                ('section', models.IntegerField()),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('CSBS_Req', models.BooleanField(default=False)),
                ('CSBS_Elec', models.BooleanField(default=False)),
                ('CSBA_Req', models.BooleanField(default=False)),
                ('CSBA_Elec', models.BooleanField(default=False)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('date_start', models.DateField(default=datetime.date(2021, 1, 6))),
                ('date_end', models.DateField(default=datetime.date(2021, 4, 23))),
                ('enrollment_capacity', models.IntegerField()),
                ('enrollment_number', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=10)),
                ('hasRecitation', models.BooleanField(default=False)),
                ('recitation_time_start', models.TimeField(blank=True, null=True)),
                ('recitation_time_end', models.TimeField(blank=True, null=True)),
                ('recitation_location', models.CharField(blank=True, max_length=10)),
                ('recommended_semester', models.IntegerField(blank=True, null=True)),
                ('lec_mo', models.BooleanField(default=False)),
                ('lec_tu', models.BooleanField(default=False)),
                ('lec_we', models.BooleanField(default=False)),
                ('lec_th', models.BooleanField(default=False)),
                ('lec_fr', models.BooleanField(default=False)),
                ('rec_mo', models.BooleanField(default=False)),
                ('rec_tu', models.BooleanField(default=False)),
                ('rec_we', models.BooleanField(default=False)),
                ('rec_th', models.BooleanField(default=False)),
                ('rec_fr', models.BooleanField(default=False)),
                ('lec_days', models.CharField(blank=True, max_length=14)),
                ('rec_day', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('FSUID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('office', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('FSUID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FSUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.student')),
                ('course_reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.professor'),
        ),
    ]
