# Generated by Django 3.1.2 on 2020-11-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default='Spring', max_length=6),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
